; <PROGRAM NAME> - An Operating System for learning purpose
; Written in 2012 by <AUTHOR NAME> <AUTHOR E-MAIL ADDRESS>
;
; To the extent possible under law, the author(s) have dedicated
; all copyright and related and neighboring rights to this software
; to the public domain worldwide. This software is distributed
; without any warranty.
; You should have received a copy of the CC0 Public Domain Dedication
; along with this software.
; If not, see http://creativecommons.org/publicdomain/zero/1.0/

SUCCESS = 0
UNSPECIFIC_ERROR = 1
INVALID_PATH = 2
ARRAY_INDEX_OUT_OF_RANGE = 3
NOT_LARGE_ENOUGH = 4
INVALID_PARAMETER = 5
INVALID_COUNT = 6
FORMAT_NOT_SUPPORTED = 7
BUFFER_EMPTY = 8
STRING_IS_NOT_A_NUMBER = 9
NULL_STRING = 10
UNSUPPORTED_FUNCTION = 11
NO_FREE_MEMORY = 12
FILE_NOT_FOUND = 13
EMPTY_FILE = 14
MEMORY_ENTRY_NOT_FOUND = 15
NON_POSITIVE_SIZE = 16
MASTER_TABLE_IS_FULL = 17