; <PROGRAM NAME> - An Operating System for learning purpose
; Written in 2012 by <AUTHOR NAME> <AUTHOR E-MAIL ADDRESS>
;
; To the extent possible under law, the author(s) have dedicated
; all copyright and related and neighboring rights to this software
; to the public domain worldwide. This software is distributed
; without any warranty.
; You should have received a copy of the CC0 Public Domain Dedication
; along with this software.
; If not, see http://creativecommons.org/publicdomain/zero/1.0/

SUCCESS = 0
UNSPECIFIC_ERROR = -1
INVALID_PATH = -2
ARRAY_INDEX_OUT_OF_RANGE = -3
RESULT_OVERFLOW = -4
INVALID_PARAMETER = -5
INVALID_COUNT = -6
FORMAT_NOT_SUPPORTED = -7